sim_param : 
  isLeft : True
  isWithMass : True
  TIME_SPAN : 10.0
  TIME_INTERVAL : 0.01
rmp_param : 
  -  # 1
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 2
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data :
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 3
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 4
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 5
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 6
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 7
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 8
    goal_attractor :
      name : 'fromGDS'
      data : 
        max_speed : 10.0
        gain : 20.0
        f_alpha : 0.15
        sigma_alpha : 2.0
        sigma_gamma : 2.0
        wu : 1.0
        wl : 0.01
        alpha : 0.15
        epsilon : 1.0e-5
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # ジョイント制限
    joint_limit_avoidance :
      name : 'Original'
      data : 
        gamma_p : 0.05
        gamma_d : 0.1
        lambda : 0.1
env_param :
  goal :
    name : 'static'
    data :
      x : 0.5
      y : -0.9
      z : 1.1
  obstacle :
    # -
    #   name : 'point'
    #   data :
    #     x : 0.25e+0
    #     y : -0.4e+0
    #     z : 1.0e+0
    -
      name : 'plane'
      data :
        x : 0.25
        y : -0.5
        z : 1.0
        lx : 1.0
        ly : 0.5
        alpha : 0.0
        beta : 0.0
        gamma : 0.0
        n : 100