sim_param : 
  isLeft : True
  isWithMass : True
  saveRmpData : True
  TIME_SPAN : 60.0
  TIME_INTERVAL : 0.01
rmp_param : 
  -  # 1
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 2
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data :
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 3
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 4
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 5
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 6
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 7
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.1
  -  # 8
    goal_attractor :
      name : 'fromGDS'
      data : 
        max_speed : 10.0
        gain : 20.0
        f_alpha : 0.15
        sigma_alpha : 2.0
        sigma_gamma : 2.0
        wu : 1.0
        wl : 0.01
        alpha : 0.15
        epsilon : 1.0e-5
    collision_avoidance :
      name : 'fromGDS'
      data : 
        rw : 0.5
        sigma : 1.0
        alpha : 0.01
  -  # ジョイント制限
    joint_limit_avoidance :
      # name : 'Original'
      # data : 
      #   gamma_p : 0.05
      #   gamma_d : 0.1
      #   lambda : 0.1
      name : "fromGDS"
      data : 
        gamma_p : 0.05
        gamma_d : 0.01
        lambda : 1.0
        sigma : 0.1
env_param :
  goal :
    name : 'static'
    data :
      x : 0.5
      y : -0.8
      z : 1.2
  obstacle :
    -
      name : 'cylinder'
      data :
        r : 0.1
        L : 1.0
        x : 0.25
        y : -0.8
        z : 1.0
        n : 100
        alpha : 0.0
        beta : 0.0
        gamma : 0.0
    -
      name : 'cylinder'
      data:
        r : 0.1
        L : 1.0
        x : 0.25
        y : -0.8
        z : 1.0
        n : 100
        alpha : 0.0
        beta : 90.0
        gamma : 0.0