# 基本
sim_param : 
  isLeft : True
  TIME_INTERVAL : 10
  TIME_INTERVAL : 0.05
rmp_param : 
  -  # 1
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 2
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 3
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 4
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 5
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 6
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 7
    goal_attractor : # None
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # 8
    goal_attractor :
      name : 'Original'
      attract_max_speed : 2
      attract_gain : 10
      attract_a_damp_r : 0.15
      attract_sigma_W : 1
      attract_sigma_H : 1
      attract_A_damp_r : 5
    collision_avoidance :
      name : 'fromGDS'
      rw : 0.5
      sigma : 1
      alpha : 0.5
  -  # ジョイント制限
    joint_limit_avoidance :
      name : 'Original'
      jl_gamma_p : 0.05
      jl_gamma_d : 0.1
      jl_lambda : 0.7
env_param :
  goal :
    name : 'static'
    center : [[0.3, -0.75, 1]]
  obstacle :
    -
      name : 'cylinder'
      data :
        r : 0.1
        L : 1.0
        center : [[0.25, -0.4, 1]]
        n : 1
        theta : 0
        phi : 90
        zeta : 0
    -
      name : 'cylinder'
      data:
        r : 0.1
        L : 1.0
        center : [[0.25, -0.4, 1]]
        n : 1
        theta : 90
        phi : 0
        zeta : 0
